version: 2.1

executors:
  ios-executor:
    macos:
      xcode: 26.4.0

jobs:
  build-and-test:
    executor: ios-executor
    steps:
      - checkout
      - run:
          name: Resolve Swift Package Dependencies
          command: |
            xcodebuild -resolvePackageDependencies -project VIPERConcurrency.xcodeproj -scheme VIPERConcurrency
      - run:
          name: Build
          command: |
            xcodebuild -project VIPERConcurrency.xcodeproj -scheme VIPERConcurrency build

workflows:
  version: 2
  build-test-pipeline:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main