version: 2.1

orbs:
  macos: circleci/macos@2.5.2

executors:
  ios-executor:
    macos:
      xcode: 26.3.0

jobs:
  build-and-test:
    executor: ios-executor
    steps:
      - macos/preboot-simulator:
          version: "26.2"
          platform: "iOS"
          device: "iPhone 17 Pro"
      - checkout
      - run:
          name: Resolve Swift Package Dependencies
          command: |
            xcodebuild -resolvePackageDependencies -project VIPERConcurrency.xcodeproj -scheme VIPERConcurrency
      - run:
          name: Build
          command: |
            xcodebuild -project VIPERConcurrency.xcodeproj -scheme VIPERConcurrency -destination 'platform:iOS Simulator, OS:26.4.1, name:iPhone 17' build

workflows:
  version: 2
  build-test-pipeline:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main